name: NPC
version: '${version}'
main: tigoku.npc.Npc
api-version: '1.20'
authors: [ Tigoku ]

description: Villager-based NPCs with GUI trade editor

commands:
  npc:
    description: Manage NPCs and their custom trades
    usage: /npc

permissions:
  npc.admin:
    description: Full access to the NPC plugin
    default: op
  npc.create:
    description: Create NPCs
    default: op
  npc.remove:
    description: Remove NPCs
    default: op
  npc.edit:
    description: Edit NPC trades via GUI
    default: op
  npc.list:
    description: Open NPC list GUI
    default: op
  npc.tp:
    description: Teleport to an NPC
    default: op
  npc.reload:
    description: Reload the plugin
    default: op
  npc.spawn:
    description: Force spawn an NPC
    default: op
  npc.despawn:
    description: Force despawn an NPC
    default: op
  npc.use:
    description: Use NPCs (open trading UI)
    default: true
